-- SDH Portal VAA - Supabase schema v1
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text default 'admin',
  created_at timestamptz default now()
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  code text unique not null,
  full_name text not null,
  program text,
  cohort text,
  email text,
  phone text,
  status text default 'Đang học',
  created_at timestamptz default now()
);

create table if not exists phd_students (
  id bigint generated by default as identity primary key,
  code text unique not null,
  full_name text not null,
  topic text,
  supervisor text,
  status text default 'Đang học',
  created_at timestamptz default now()
);

create table if not exists faculty (
  id bigint generated by default as identity primary key,
  code text unique,
  full_name text not null,
  degree text,
  title text,
  email text,
  phone text,
  created_at timestamptz default now()
);

create table if not exists councils (
  id bigint generated by default as identity primary key,
  student text,
  title text,
  defense_date date,
  room text,
  status text default 'Sắp bảo vệ',
  created_at timestamptz default now()
);

alter table students enable row level security;
alter table phd_students enable row level security;
alter table faculty enable row level security;
alter table councils enable row level security;

create policy "Authenticated users can read students" on students for select to authenticated using (true);
create policy "Authenticated users can insert students" on students for insert to authenticated with check (true);
create policy "Authenticated users can update students" on students for update to authenticated using (true);
create policy "Authenticated users can delete students" on students for delete to authenticated using (true);
